server:
  version: "Vitalis-api-v1.0.0"
  port: ":8000"

logger:
  level: "debug" # debug, info

cors:
  allow_origins:
    - "*"
  allow_methods:
    - "GET"
    - "POST"
    - "PATCH"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
  expose_headers: []
  allow_credentials: false
  max_age: 43200 # 12 часов в секундах

